name: trapeza_app
description: "Trapeza - you make the rules."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.9.0 <4.0.0" # dart minimum version
  flutter: ">=3.38.0 <4.0.0" # flutter minimum version

dependencies:
  fast_immutable_collections: ^11.1.0
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  commitlint_cli: ^0.8.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  husky: ^0.1.7

flutter:
  fonts:
    - family: "Nunito"
      fonts:
        - asset: "assets/fonts/Nunito/Nunito-Regular.ttf"
        - asset: "assets/fonts/Nunito/Nunito-Bold.ttf"
          weight: 700
  generate: true
  uses-material-design: true
